Animal rehab data exploration and visualisation

In [57]:
import pandas as pd
import numpy as np
data = pd.read_csv("Urban_Park_Ranger_Animal_Condition_Response.csv")
print(data.shape)
data.head(20)

(2609, 22)

,Date and Time of initial call,Date and time of Ranger response,Borough,Property,Location,Species Description,Call Source,Species Status,Animal Condition,Duration of Response,...,311SR Number,Final Ranger Action,# of Animals,PEP Response,Animal Monitored,Rehabilitator,Hours spent monitoring,Police Response,ESU Response,ACC Intake Number
0,06/23/2021 04:45:00 PM,06/24/2021 08:00:00 AM,Brooklyn,Sternberg Park,Inside locked athletic field under construction,Chukar,Other,Exotic,Healthy,6.00,...,311-06712416,ACC,6.0,False,False,NaN,NaN,False,False,163537
1,06/24/2021 10:00:00 AM,06/24/2021 11:00:00 AM,Bronx,Haffen Park,Haffen Pool,Sparrow,Central,Native,Healthy,1.75,...,311-06714879,Rehabilitator,4.0,False,False,NaN,NaN,False,False,NaN
2,06/23/2021 02:30:00 PM,06/23/2021 02:30:00 PM,Bronx,Pelham Bay Park,Pelham Bay South,White-tailed Deer,Employee,Native,NaN,1.00,...,NaN,Unfounded,0.0,False,False,NaN,NaN,False,False,NaN
3,06/23/2021 01:00:00 PM,06/23/2021 01:10:00 PM,Staten Island,Willowbrook Park,The carousel,Raccoon,Employee,Native,NaN,2.00,...,NaN,Unfounded,0.0,False,False,NaN,NaN,False,False,NaN
4,06/23/2021 09:20:00 AM,06/23/2021 09:20:00 AM,Queens,Judge Moses Weinstein Playground,Garbage can,Virginia Opossum,Central,Native,Healthy,2.25,...,311-06699415,ACC,1.0,False,False,NaN,NaN,False,False,119833
5,06/23/2021 09:00:00 AM,06/23/2021 09:10:00 AM,Staten Island,Clove Lakes Park,Martling Pond on shore,Domestic Duck,Employee,Domestic,Healthy,1.25,...,311-06700321,ACC,1.0,False,False,NaN,NaN,False,False,119822
6,06/23/2021 05:30:00 AM,06/23/2021 08:20:00 AM,Staten Island,Willowbrook Park,Pond,Canada Goose,Employee,Native,Injured,0.50,...,NaN,Unfounded,0.0,False,False,NaN,NaN,False,False,NaN
7,06/22/2021 03:00:00 PM,06/22/2021 03:00:00 PM,Queens,Travers Park,78th Street Plaza,Cat,Public,Domestic,Unhealthy,1.00,...,NaN,Unfounded,0.0,False,False,NaN,NaN,False,False,NaN
8,06/22/2021 03:30:00 PM,06/22/2021 03:30:00 PM,Brooklyn,Prospect Park,V/O Drummers Circle,Dog,Employee,Domestic,Injured,0.50,...,NaN,ACC,1.0,True,False,NaN,NaN,False,False,NaN
9,06/22/2021 11:30:00 AM,06/22/2021 11:30:00 AM,Manhattan,Highbridge Park,Coogan's Bluff Playground,Dog,Central,Domestic,NaN,0.75,...,NaN,Unfounded,0.0,False,False,NaN,NaN,False,False,NaN
10,06/22/2021 11:55:00 AM,06/22/2021 11:55:00 AM,Queens,Forest Park,Giovanelli Playground,Eastern Rat Snake,Central,Native,Healthy,2.00,...,311-06691186,Relocated/Condition Corrected,1.0,False,False,NaN,NaN,False,False,NaN
11,06/22/2021 12:00:00 PM,06/22/2021 12:00:00 PM,Manhattan,Inwood Hill Park,214th and Seaman Ave,Eastern Gray Squirrel,Employee,Native,Injured,0.50,...,NaN,Advised/Educated others,1.0,False,True,NaN,0.5,False,False,NaN
12,06/22/2021 11:30:00 AM,06/22/2021 12:00:00 PM,Brooklyn,Marine Park,Salt Marsh Nature Trail,Domestic Rabbit,Employee,Domestic,Healthy,2.00,...,NaN,Unfounded,0.0,False,False,NaN,NaN,False,False,NaN
13,06/21/2021 02:02:00 PM,06/21/2021 02:02:00 PM,Queens,Queens Botanical Garden,Education building,Northern Cardinal,Central,Native,Injured,2.75,...,311-06682248,Rehabilitator,1.0,False,False,Wild Bird Fund,NaN,False,False,NaN
14,06/21/2021 02:45:00 PM,06/21/2021 02:50:00 PM,Staten Island,Franklin D. Roosevelt Boardwalk and Beach,PEP Trailer,Mallard Duck,Employee,Native,Healthy,1.50,...,311-06684155,ACC,1.0,True,False,NaN,NaN,False,False,52440
15,06/21/2021 08:50:00 AM,06/21/2021 03:50:00 PM,Bronx,Van Cortlandt Park,Van Cortlandt Lake and its trails,Double-crested Cormorant,"Conservancies/""Friends of"" Groups",Native,Healthy,0.75,...,311-06684-300,Monitored Animal,1.0,False,True,NaN,3.0,False,False,NaN
16,06/21/2021 09:20:00 AM,06/21/2021 12:00:00 PM,Manhattan,Central Park,West 97 St entrance,Raccoon,Central,Native,Injured,0.50,...,311- 06678452,Unfounded,0.0,False,False,NaN,NaN,False,False,NaN
17,06/21/2021 08:50:00 AM,06/21/2021 09:05:00 AM,Bronx,Van Cortlandt Park,Adjacent to Golf Clubhouse past golf cart parking,Double-crested Cormorant,"Conservancies/""Friends of"" Groups",Native,Injured,0.30,...,NaN,Unfounded,0.0,False,False,NaN,NaN,False,False,NaN
18,06/16/2021 12:00:00 PM,06/16/2021 01:00:00 PM,Brooklyn,Prospect Park,Prospect Lake near LeFrak Center,Domestic Duck,"Conservancies/""Friends of"" Groups",Domestic,Unhealthy,2.00,...,311-06621675,ACC,1.0,False,False,NaN,NaN,False,False,119360
19,06/20/2021 09:00:00 AM,06/20/2021 03:00:00 PM,Manhattan,Inwood Hill Park,Northwest edge of Gaelic Field,Common Snapping Turtle,Employee,Native,NaN,1.00,...,NaN,Unfounded,0.0,False,False,NaN,NaN,False,False,NaN

Preprocess data

In [58]:
reldf = data[['Date and Time of initial call', 'Date and time of Ranger response', 'Species Status', 'Animal Class', 'Age', 'Animal Condition', '# of Animals', 'Call Source', 'Final Ranger Action', 'Hours spent monitoring']]
reldf.columns = ['Time of call', 'Time of response', 'Species Type', 'Animal Class', 'Age', 'Animal Condition', 'Count of animals', 'Call Source', 'Final Ranger Action', 'Monitoring hours']
reldf['Time of call'] = pd.to_datetime(reldf['Time of call'])
reldf['Time of response'] = pd.to_datetime(reldf['Time of response'])
reldf['Event year'] = reldf['Time of response'].dt.year
reldf['Time to react'] = reldf['Time of response'] - reldf['Time of call']
reldf['Time to react'] = reldf['Time to react'].dt.seconds/60
reldf['Time to react'] = pd.to_numeric(reldf['Time to react'], errors='coerce').fillna(0).astype(np.int32)
animaltypes = {'Birds' : 'Birds',
                'Coyotes' : 'Mammals',
                'Deer' : 'Mammals',
                'Domestic' : 'Domestic',
                'Domestic;#Birds' : 'Domestic',
                'Domestic;#Small Mammals-non RVS' : 'Domestic',
                'Fish-numerous quantity' : 'Fish',
                'Marine Mammals-seals only' : 'Mammals',
                'Raptors' : 'Birds',
                'Small Mammals-RVS' : 'Mammals',
                'Small Mammals-non RVS' : 'Mammals',
                'Terrestrial Reptile or Amphibian' : 'Herps',
                'Birds;#Domestic' : 'Birds',
                'Fish-numerous quantity;#Terrestrial Reptile or Amphibian' : 'Fish',
                'Marine Mammals-whales, Dolphin' : 'Mammals',
                'Marine Reptiles' : 'Herps',
                'Small Mammals-RVS;#Domestic' : 'Mammals',
                'Non Native Fish-(invasive)' : 'Fish',
                'Rare, Endangered, Dangerous' : 'Rare'}
reldf['Animal Class'] = reldf['Animal Class'].map(animaltypes)
reldf.to_csv("outputtable.csv", index=False)
reldf.head(100)

/var/folders/p9/frtk4fwx3nzdw7xqnvjwz2sw0000gn/T/ipykernel_8885/3063468877.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  reldf['Time of call'] = pd.to_datetime(reldf['Time of call'])
/var/folders/p9/frtk4fwx3nzdw7xqnvjwz2sw0000gn/T/ipykernel_8885/3063468877.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  reldf['Time of call'] = pd.to_datetime(reldf['Time of call'])
/var/folders/p9/frtk4fwx3nzdw7xqnvjwz2sw0000gn/T/ipykernel_8885/3063468877.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  reldf['Time of response'] = pd.to_datetime(reldf['Time of response'])
/var/folders/p9/frtk4fwx3nzdw7xqnvjwz2sw0000gn/T/ipykernel_8885/3063468877.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  reldf['Event year'] = reldf['Time of response'].dt.year
/var/folders/p9/frtk4fwx3nzdw7xqnvjwz2sw0000gn/T/ipykernel_8885/3063468877.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  reldf['Time to react'] = reldf['Time of response'] - reldf['Time of call']
/var/folders/p9/frtk4fwx3nzdw7xqnvjwz2sw0000gn/T/ipykernel_8885/3063468877.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  reldf['Time to react'] = reldf['Time to react'].dt.seconds/60
/var/folders/p9/frtk4fwx3nzdw7xqnvjwz2sw0000gn/T/ipykernel_8885/3063468877.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  reldf['Time to react'] = pd.to_numeric(reldf['Time to react'], errors='coerce').fillna(0).astype(np.int32)
/var/folders/p9/frtk4fwx3nzdw7xqnvjwz2sw0000gn/T/ipykernel_8885/3063468877.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  reldf['Animal Class'] = reldf['Animal Class'].map(animaltypes)

,Time of call,Time of response,Species Type,Animal Class,Age,Animal Condition,Count of animals,Call Source,Final Ranger Action,Monitoring hours,Event year,Time to react
0,2021-06-23 16:45:00,2021-06-24 08:00:00,Exotic,Birds,Adult,Healthy,6.0,Other,ACC,NaN,2021,915
1,2021-06-24 10:00:00,2021-06-24 11:00:00,Native,Birds,Infant,Healthy,4.0,Central,Rehabilitator,NaN,2021,60
2,2021-06-23 14:30:00,2021-06-23 14:30:00,Native,Mammals,Juvenile,NaN,0.0,Employee,Unfounded,NaN,2021,0
3,2021-06-23 13:00:00,2021-06-23 13:10:00,Native,Mammals,Adult;#Juvenile,NaN,0.0,Employee,Unfounded,NaN,2021,10
4,2021-06-23 09:20:00,2021-06-23 09:20:00,Native,Mammals,Juvenile,Healthy,1.0,Central,ACC,NaN,2021,0
...,...,...,...,...,...,...,...,...,...,...,...,...
95,2021-05-29 13:00:00,2021-05-29 15:30:00,Domestic,Domestic,Adult,Healthy,3.0,"Conservancies/""Friends of"" Groups",ACC,NaN,2021,150
96,2021-05-29 10:57:00,2021-05-28 11:08:00,Native,Birds,Infant,Injured,0.0,Public,Unfounded,NaN,2021,11
97,2021-05-28 09:15:00,2021-05-28 09:30:00,Invasive,Birds,Adult,Injured,1.0,Public,Relocated/Condition Corrected,NaN,2021,15
98,2021-05-28 14:00:00,2021-05-28 14:00:00,Domestic,Domestic,Adult,Healthy,3.0,Public,ACC,NaN,2021,0
99,2021-05-28 17:00:00,2021-05-28 17:00:00,Native,Birds,Adult,Injured,1.0,Public,Monitored Animal,0.5,2021,0

1) How has the number of animals sent to rehabilitators or animal care centres changed over time?

In [59]:
filtered_df = reldf[reldf['Final Ranger Action'].isin(['ACC', 'Rehabilitator'])]
animalcountchange = filtered_df.groupby(['Species Type', 'Event year', 'Final Ranger Action']).agg({'Count of animals': 'sum', 'Time to react': 'mean'}).reset_index()
animalcountchange.to_csv("animalcountchange.csv", index=False)

2) How has the type of animal being reported changed over time?

In [60]:
animaltypechange = reldf.groupby(['Species Type', 'Event year']).agg({'Count of animals': 'sum'}).reset_index()
animaltypechange.to_csv("animaltypechange.csv", index=False)

3) How has the source of information (call source) changed over time?

In [61]:
callsourcechange = reldf.groupby(['Species Type', 'Event year', 'Call Source']).agg({'Count of animals':'count'}).reset_index()
callsourcechange.to_csv("callsourcechange.csv")

In [62]:
filtered_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1058 entries, 0 to 2606
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Time of call         1058 non-null   datetime64[ns]
 1   Time of response     1058 non-null   datetime64[ns]
 2   Species Type         1058 non-null   object
 3   Animal Class         1058 non-null   object
 4   Age                  1058 non-null   object
 5   Animal Condition     1051 non-null   object
 6   Count of animals     1057 non-null   float64
 7   Call Source          1058 non-null   object
 8   Final Ranger Action  1058 non-null   object
 9   Monitoring hours     54 non-null     float64
 10  Event year           1058 non-null   int32
 11  Time to react        1058 non-null   int32
dtypes: datetime64[ns](2), float64(2), int32(2), object(6)
memory usage: 99.2+ KB